/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-05-08 17:31:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>Profile</title>\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write("        /* Custom CSS for demonstration */\r\n");
      out.write("        #myDiv {\r\n");
      out.write("            display: none;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        <style>\r\n");
      out.write("        /* Custom CSS for demonstration */\r\n");
      out.write("        #myDiv1 {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 String name = String.valueOf(session.getAttribute("name1")); 
      out.write("\r\n");
      out.write("<h2 class =\"mb-4 mt-4 fst-italic text-primary text-center\">Welcome : ");
      out.print(name );
      out.write("</h2>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-body-tertiary mb-5\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"/\"><b><i>Bank App</i></b></a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarText\" aria-controls=\"navbarText\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse ms-3\" id=\"navbarText\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active fst-italic align-bottom d-flex justify-content-end link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\" id=\"myAnchor\" onclick=\"showDiv()\" >Add New Customer</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item fst-italic align-bottom d-flex justify-content-end link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\" onclick=\"hideDiv()\">Add Bank Accont</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item fst-italic align-bottom d-flex justify-content-end link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">View Customers</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item fst-italic align-bottom d-flex justify-content-end link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">View Transactions</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <span class=\"navbar-text\">\r\n");
      out.write("        <b>Admin Home Page &nbsp;</b>\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\" translate-middle  p-4 m-5 rounded bg-white\" id=\"myDiv\">\r\n");
      out.write("<h2 class =\"mb-4 fst-italic text-primary ms-5 ps-5\">Add New Customer</h2>\r\n");
      out.write("<form action=\"LoginController\" class=\"m-5 ps-5 pe-5\">\r\n");
      out.write("<div class=\"input-group mb-3\">\r\n");
      out.write("  <span class=\"input-group-text\">First & Last Name</span>\r\n");
      out.write("  <input type=\"text\" aria-label=\"text\" class=\"form-control\" placeholder=\"First Name\" required>\r\n");
      out.write("   <input type=\"text\" aria-label=\"text\" class=\"form-control\" placeholder=\"Last Name\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"input-group mb-3\">\r\n");
      out.write("  <span class=\"input-group-text\">Login Id</span>\r\n");
      out.write("  <input type=\"email\" aria-label=\"Email\" class=\"form-control\" placeholder=\"Enter Your Email\" required>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"input-group mb-3\">\r\n");
      out.write("  <span class=\"input-group-text\">Password</span>\r\n");
      out.write("  <input type=\"password\" aria-label=\"password\" class=\"form-control\" placeholder=\"Create New Password\" required>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"vstack gap-2 col-md-12 mx-auto\">\r\n");
      out.write("<input type =\"submit\" value =\"Sign Up\" class=\"btn btn-success\">\r\n");
      out.write("<input type =\"reset\" value =\"Cancel\" class = \"btn btn-danger\">\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id =\"myDiv1\">\r\n");
      out.write("<h2 class =\"mb-4 fst-italic text-primary ms-5 ps-5\">Add Bank Account</h2>\r\n");
      out.write("<form action=\"#\" class=\"m-5 ps-5 pe-5\">\r\n");
      out.write("<div class=\"vstack gap-2 col-md-12 mx-auto\">\r\n");
      out.write("<div class=\"form-floating mb-3 border border-success-subtle\">\r\n");
      out.write("  <input type=\"text\" class=\"form-control\" id=\"floatingInput\" placeholder=\"c\">\r\n");
      out.write("  <label for=\"floatingInput\">Search by Customer Id</label>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"submit\" value=\"Search\" class=\"btn btn-success align-self-end justify-content-end pe-5 ps-5 rounded-5\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function showDiv() {\r\n");
      out.write("        var divElement = document.getElementById(\"myDiv\");\r\n");
      out.write("        var divElement1 = document.getElementById(\"myDiv1\");\r\n");
      out.write("        if(divElement.style.display = \"inline\"){\r\n");
      out.write("        	divElement1.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function hideDiv() {\r\n");
      out.write("        var divElement = document.getElementById(\"myDiv\");\r\n");
      out.write("        var divElement1 = document.getElementById(\"myDiv1\");\r\n");
      out.write("        if (divElement.style.display = \"none\") {\r\n");
      out.write("        	divElement1.style.display = \"inline\";\r\n");
      out.write("		}\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
